Index width field
maiconpinto/cakephp-adminlte-theme pull request #22
Opened 2016-10-20 18:34 UTC by ooprogramador

Adicionado width no campo de busca para que ele nao sobreponha o titulo do grid.

2016-10-21 12:37 UTC, maiconpinto approved these changes

2016-10-21 12:40 UTC, maiconpinto requested changes
Oi Robson, podemos ver outra forma de resolver isso? Colocar um style inline não parece um padrão muito bom, além de não ser responsivo. De repente podemos pensar em criar uma class específica para fazer este ajuste, o que acha?

2016-10-23 04:32 UTC, ooprogramador commented
Perfeito, até pensei em fazer isso, mas como no tema original a solução proposta foi com width, repliquei. Mas vou ver algo e comito. Vlw :)

2016-10-24 02:01 UTC, merged

2016-10-24 02:01 UTC, maiconpinto commented
Oi Robson, eu vi que no original atualmente é assim mesmo, então vamos seguir o padrão. Minha ideia é manter atualizado, mas preciso parar mais tempo e resolver isso. Por enquanto, muito obrigado pela contribuição.